version: '3'
services:
  backend:
    build: ./backend
    image: weatherapp_backend
    env_file:
      - backend/.env
    ports:
      - 9000:9000
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    image: weatherapp_frontend
    ports:
      - 80:8000
    volumes:
      - ./frontend:/usr/src/app